document.getElementById("submit").addEventListener("click", getFortune);

function getFortune() {
    const fortunes = [
        "Today is your lucky day, seize every opportunity!",
        "A new adventure awaits you, be ready to explore.",
        "Challenges may arise, but your resilience will shine.",
        "Love is in the air, keep your heart open.",
        "Financial stability is on the horizon, stay prudent.",
        "A kind gesture will bring unexpected rewards.",
        "Trust your intuition, it will guide you well.",
        "Hard work today will pay off tomorrow.",
        "A friend will offer valuable advice, listen closely.",
        "Take a moment to relax, balance is key.",
        "Unexpected news will brighten your day.",
        "Stay cautious, small obstacles may appear.",
        "Your creativity will lead to exciting outcomes.",
        "A long-awaited goal is within reach, keep pushing.",
        "Harmony will prevail in your relationships.",
        "Be patient, good things are coming your way.",
        "A bold decision will open new doors.",
        "Avoid conflicts, diplomacy is your strength today.",
        "Your confidence will inspire those around you.",
        "A small risk could lead to big rewards.",
        "Focus on self-care, your energy needs recharging.",
        "An old friend may reconnect, cherish the moment.",
        "Stay organized, clarity will boost your success.",
        "A creative project will gain recognition soon.",
        "Beware of distractions, stay focused on your goals.",
        "A surprise gift or gesture will lift your spirits.",
        "Your determination will overcome any challenge.",
        "Take time to reflect, wisdom comes from within.",
        "A new skill you learn will prove valuable.",
        "Stay humble, your kindness will be appreciated.",
        "An opportunity for growth is just around the corner.",
        "Avoid impulsive decisions, think things through.",
        "Your optimism will attract positive energy.",
        "A family member will share joyful news.",
        "Stay adaptable, change is coming your way.",
        "Your efforts will be recognized, keep it up!",
        "A moment of courage will lead to success.",
        "Be mindful of your words, they carry weight today.",
        "A financial opportunity may arise, evaluate carefully.",
        "Your patience will be tested, but you'll prevail.",
        "A romantic encounter could spark excitement.",
        "Stay true to your values, they will guide you.",
        "A small act of kindness will make a big difference.",
        "Your hard work will soon yield tangible results.",
        "Avoid overthinking, trust the process.",
        "A new connection will enrich your life.",
        "Stay grounded, balance will bring peace.",
        "Your leadership will shine in a group setting.",
        "A past effort will bring rewards today.",
        "Embrace change, it will lead to growth.",
        "A new perspective will solve an old problem.",
        "Your generosity will be returned tenfold.",
        "A quiet moment will bring clarity to your thoughts.",
        "An unexpected ally will support your goals.",
        "Stay curious, new knowledge awaits you.",
        "A journey will broaden your horizons.",
        "Your smile will brighten someone's day.",
        "A challenge will reveal your hidden strengths.",
        "Take a leap of faith, success is near.",
        "A meaningful conversation will deepen a bond.",
        "Your discipline will lead to great achievements.",
        "A moment of gratitude will shift your perspective.",
        "An opportunity to learn will present itself.",
        "Your honesty will earn someone's trust.",
        "A creative idea will spark inspiration.",
        "Stay calm, solutions will emerge naturally.",
        "A shared experience will strengthen a friendship.",
        "Your focus will lead to a breakthrough.",
        "A small step forward will build momentum.",
        "An act of courage will change your path.",
        "Your enthusiasm will motivate others.",
        "A moment of stillness will recharge your spirit.",
        "A new hobby will bring unexpected joy.",
        "Your persistence will unlock new possibilities.",
        "A kind word will make a lasting impact.",
        "An old memory will bring warmth to your heart.",
        "Your adaptability will turn challenges into opportunities.",
        "A chance encounter will lead to inspiration.",
        "Your effort will lay the foundation for success.",
        "A moment of reflection will reveal your next step.",
        "Your compassion will heal a strained relationship.",
        "A new goal will ignite your passion.",
        "Your determination will clear any obstacle.",
        "A gesture of goodwill will strengthen ties.",
        "Your vision will guide you to new heights.",
        "A moment of patience will prevent a mistake.",
        "Your energy will attract exciting opportunities.",
        "A small victory will boost your confidence.",
        "Your wisdom will resolve a difficult situation.",
        "A new project will showcase your talents.",
        "Your kindness will inspire others to follow suit.",
        "A change in routine will spark creativity.",
        "Your focus on details will lead to perfection.",
        "A heartfelt apology will mend a rift.",
        "Your ambition will open unexpected doors.",
        "A quiet act of kindness will ripple outward.",
        "Your clarity of purpose will drive success.",
        "A new friendship will bring joy to your life.",
        "Your courage will inspire someone close to you.",
        "A moment of humor will lighten the mood.",
        "Your hard work will earn you admiration.",
        "A fresh start will renew your enthusiasm.",
        "Your intuition will lead you to the right choice.",
        "A shared goal will unite you with others.",
        "Your optimism will overcome any doubt.",
        "A small sacrifice will yield great rewards.",
        "Your creativity will solve a complex problem.",
        "A moment of generosity will create lasting goodwill.",
        "Your discipline will keep you on track.",
        "A new experience will expand your worldview.",
        "Your sincerity will deepen a connection.",
        "A bold move will set you apart.",
        "Your patience will uncover hidden opportunities.",
        "A kind deed will return to you unexpectedly.",
        "Your focus will turn dreams into reality.",
        "A moment of vulnerability will build trust.",
        "Your determination will silence doubters.",
        "A new insight will change your approach.",
        "Your warmth will comfort someone in need.",
        "A calculated risk will pay off handsomely.",
        "Your perseverance will conquer all setbacks.",
        "A shared laugh will strengthen a bond.",
        "Your vision will inspire a team effort.",
        "A moment of courage will define your day.",
        "Your humility will earn you respect.",
        "A new challenge will reveal your potential.",
        "Your generosity will create a ripple effect.",
        "A quiet reflection will spark a brilliant idea.",
        "Your effort will build a lasting legacy.",
        "A sincere compliment will brighten someone's day.",
        "Your focus will cut through distractions.",
        "A new opportunity will test your skills.",
        "Your kindness will bridge a gap.",
        "A moment of clarity will guide your decisions.",
        "Your resilience will overcome adversity.",
        "A shared vision will lead to success.",
        "Your patience will reveal a hidden truth.",
        "A small gesture will create a big impact.",
        "Your creativity will shine in unexpected ways.",
        "A new path will lead to fulfillment.",
        "Your determination will move mountains.",
        "A moment of gratitude will ground you.",
        "Your leadership will guide others to victory.",
        "A kind act will return to you in time.",
        "Your focus will unlock new doors.",
        "A new connection will spark inspiration.",
        "Your courage will break new ground.",
        "A moment of peace will restore your balance.",
        "Your effort will be rewarded with success.",
        "A sincere effort will mend a broken bond.",
        "Your optimism will light the way forward.",
        "A small change will lead to big results.",
        "Your intuition will steer you clear of trouble.",
        "A shared moment will create a lasting memory.",
        "Your persistence will achieve the impossible.",
        "A kind word will heal a wounded heart.",
        "Your vision will shape a brighter future.",
        "A moment of bravery will change everything.",
        "Your humility will open new doors.",
        "A new skill will boost your confidence.",
        "Your generosity will inspire others.",
        "A quiet moment will reveal your purpose.",
        "Your effort will transform your life.",
        "A sincere gesture will build a strong bond.",
        "Your focus will lead to a major win.",
        "A new adventure will spark your passion.",
        "Your courage will overcome all fears.",
        "A moment of kindness will change a life.",
        "Your determination will create new opportunities.",
        "A shared dream will bring you closer to others.",
        "Your patience will lead to lasting success.",
        "A small act will leave a big legacy.",
        "Your creativity will inspire a movement.",
        "A new perspective will unlock your potential.",
        "Your resilience will turn dreams into reality.",
        "A moment of gratitude will bring you peace.",
        "Your leadership will pave the way for others.",
        "A kind act will echo through time.",
        "Your focus will achieve greatness.",
        "A new journey will redefine your purpose."
    ];

    const randomFortune = fortunes[Math.floor(Math.random() * fortunes.length)];

    const today = new Date();
    const monthToday = today.getMonth();
    const dateToday = today.getDate();
    const monthNames = [
        "January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December"
    ];

    const fortuneDiv = document.getElementById("fortune");
    fortuneDiv.style.display = "block";
    fortuneDiv.innerHTML = `
        <div>
            <h2>Your Fortune on ${monthNames[monthToday]} ${dateToday}</h2>
            <p><strong>Fortune:</strong> ${randomFortune}</p>
        </div>
    `;
    console.log("Today's fortune:", randomFortune);
}